### ISSUE TITLE
pie-arm-decoder.h is not generated

### ISSUE THREAD

**Issue by techvoltage** [beehive-lab/mambo#10]
pie/pie-arm-decoder.h No such file or directory

**Comment by lgeek** [comment]
Did you run 
```git submodule init
git submodule update```

and is the `pie` directory populated?

**Comment by techvoltage** [comment]
My bad. I was on a fresh cloud instance and didn't want to go through the process of setting up git. I simply did 
`git clone https://github.com/beehive-lab/mambo`
cd mambo
`git clone https://github.com/beehive-lab/pie`
`make`
I wonder why that didn't work though
