### ISSUE TITLE
Mambo on rv32

### ISSUE THREAD

**Issue by AndHager** [beehive-lab/mambo#112]
Is it planed or even WIP to support the Risc-V 32 bit ISA?

**Comment by jkressel** [comment]
Hi @AndHager,
Thank you for your interest in using MAMBO. At the moment we do not have full support for RV32. Some partial support is present (look for `__riscv_xlen == 32` in the code) however this is largely untested as we do not have access to RV32 hardware platforms. We would like to support RV32 fully in the future and have an internal development branch, however this will not happen in 2024.

We always welcome contributions!
