### ISSUE TITLE
write_p exceeds data_p

### ISSUE THREAD

**Issue by BaeSla** [beehive-lab/mambo#131]
If the rules in mambo_register_pre_inst_cb get too long, my dbm end up in a scanner while loop like this:

![image](https://github.com/user-attachments/assets/a7d86801-6fac-4b58-b0dd-e38d9a52da9f)

(scanner_riscv.c line 1318~1321)

Even if I put in a lot of rules to analyze, is there a way to bypass that doesn't fall into that while loop?

**Comment by IgWod** [comment]
Hi @BaeSla,

For multiple reasons the maximum size of the basic block is fixed. I think you can get around it by increasing the `BASIC_BLOCK_SIZE` in `dbm.h`. Let me know if that works.

**Comment by lgeek** [comment]
Hi. You should call `mambo_reserve_cc_space(mambo_context *ctx, size_t size)` before you insert your instrumentation if you expect it to exceed `MIN_FSPACE` bytes in size (it's an ISA-specific value, but to write portable code you should consider the smallest size, which appears to be 56 bytes on RISC-V).

**Comment by BaeSla** [comment]
Hi @IgWod and @lgeek,

I solved that problem by inserting `mambo_reserve_cc_space` before my instrumentation.
Thank you both for your help!
