### ISSUE TITLE
arm system

### ISSUE THREAD

**Issue by nongiach** [beehive-lab/mambo#21]
Hey,
I figured that you have "arm system" in your prerequisites,
consider to add this to your readme.

# How to quickly install an ARM virtual machine
```sh
# pip3 install arm_now
$ arm_now start armv5-eabi
Welcome to arm_now
buildroot login: root
# uname -m
armv7l
```
source: https://github.com/nongiach/arm_now

**Comment by umarcor** [comment]
Related to #19. I could successfully start a machine inside a docker container:

```
docker run --rm -it python:3-slim-stretch bash -c "\
  apt update && \
  apt install -y xz-utils libmagic1 e2tools qemu unzip && \
  pip3 install arm_now && \
  arm_now start armv7-eabihf"
```

However, how to get mambo built and executed there?

Once I login (`buildroot login: root`), neither `git` nor `apt` are available, so I cannot get the sources.

**Comment by lgeek** [comment]
@umarcor We have a QEMU system image with MAMBO already set up for you. It's mentioned in the [tutorial](https://github.com/beehive-lab/mambo/releases/download/1/mambo_tutorial_hipeac_2018.pdf]. Pasting the relevant slide here:

Portable QEMU virtual machine image (for non-ARM hosts):
https://github.com/beehive-lab/mambo-vm/releases
To use:
# install qemu-system-aarch64
# download mambo_vm.tar.gz
mkdir mambo-vm
cd mambo-vm
tar xf /path/to/mambo_vm.tar.gz
./start_vm.sh
# SSH alarm:alarm or root:root on localhost:5040
cd /home/alarm/mambo
# make sure to change the passwords if opening SSH to the network

**Comment by nongiach** [comment]
opkg is the package manager,
opkg install git
if you have a qemu image with mambo then you are good to go, even if arm_now has few interesting features like current directory sharing ...
