### ISSUE TITLE
cannot stop main thread when running on android

### ISSUE THREAD

**Issue by whcjb** [beehive-lab/mambo#40]
hello, sorry to disturb.
i use the dbm to run multi-threads app on android, but when the created threads exit, the main thread hanged on a basic_block loop all the time,. Then i use *strace* to see the syscall, found that the main thread last syscall_no is 98, which is futex, so, how to solve the problem, need your help, thanks.

**Comment by lgeek** [comment]
Hi,

That sounds like an issue specific to your application. Any chance you could share the executable with us so we can debug it?

Thanks

**Comment by whcjb** [comment]
hi，lgeek.
The application code is simple, just create two threads and use pthread_join to wait. the code here. 
`#include <stdio.h>
#include <pthread.h>
#include <stdlib.h>
#include <unistd.h>

void print_message_func(void *ptr);

int main()
{
    int tmp1,tmp2, tmp3;
    void *retival;
    pthread_t thread1;
    pthread_t thread2;
    char *message1 = "thread1";
    char *message2 = "thread2";
    
    int ret_thread1,ret_thread2;
    ret_thread1 = pthread_create(&thread1,NULL,(void *)&print_message_func,(void *)message1);
    ret_thread2 = pthread_create(&thread2,NULL,(void *)&print_message_func,(void *)message2);
    tmp1 = pthread_join(thread1,&retival);
    tmp2 = pthread_join(thread2,&retival);
}

void print_message_func(void *ptr)
{
    int i;
    sleep(10);
}
`
i use cross-compile gcc ` aaarch64-linux-android-gcc -o mt mt.c' to compile, the ndk version is 20.
after several days' error location, i have found that when use *strace*, that is `strace -f dbm mt` on an android shell terminal, the error section of the log is this
`[pid  4995] munmap(0x7bfd5b0000, 16777216) = 0
[pid  4995] munmap(0x7bfd429000, 1601536) = 0
[pid  4995] munmap(0x7bfe5b0000, 26034176) = 0
[pid  4995] sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}, NULL) = 0
[pid  4995] munmap(0x7c00ded000, 20480) = 0
[pid  4995] set_tid_address(0)          = 4995
[pid  4995] rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2 RT_3], ~[KILL STOP RT_1 RT_2 RT_3 RT_4 RT_5], 8) = 0
[pid  4995] munmap(0x7c00df2000, 20480) = 0
[pid  4995] munmap(0x7c00df7000, 28672) = 0
[pid  4995] exit(0)                     = ?
[pid  4995] +++ exited with 0 +++
mmap(NULL, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x7c00df7000
mprotect(0x7c00df7000, 4096, PROT_NONE) = 0
prctl(PR_SET_VMA, PR_SET_VMA_ANON_NAME, 0x7c00df7000, 4096, "thread stack guard") = 0
mmap(NULL, 20480, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7c00df2000
prctl(PR_SET_VMA, PR_SET_VMA_ANON_NAME, 0x7c00df2000, 20480, "bionic TLS guard") = 0
mprotect(0x7c00df3000, 12288, PROT_READ|PROT_WRITE) = 0
prctl(PR_SET_VMA, PR_SET_VMA_ANON_NAME, 0x7c00df3000, 12288, "bionic TLS") = 0
clone(./strace: Process 4996 attached
 <unfinished ...>
[pid  4996] futex(0x7c00dfd570, FUTEX_WAIT_BITSET_PRIVATE, 2, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
[pid  4993] <... clone resumed> child_stack=0x7c00dfd4e0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7c00dfd500, tls=0x7c00dfd588, child_tidptr=0x7c00dfd500) = 4996
[pid  4993] sched_getscheduler(0)       = 0 (SCHED_OTHER)
[pid  4993] futex(0x7c00dfd570, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  4993] write(1, "--------------------------------"..., 53-----------------------------------------__NR_clone1
) = 53
[pid  4996] <... futex resumed> )       = 0
[pid  4996] mmap(NULL, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7c00ded000
[pid  4996] mprotect(0x7c00ded000, 4096, PROT_NONE) = 0
[pid  4996] sigaltstack({ss_sp=0x7c00dee000, ss_flags=0, ss_size=16384}, NULL) = 0
[pid  4996] prctl(PR_SET_VMA, PR_SET_VMA_ANON_NAME, 0x7c00dee000, 16384, "thread signal stack") = 0
[pid  4996] prctl(PR_SET_VMA, PR_SET_VMA_ANON_NAME, 0x7c00ded000, 4096, "thread signal stack guard") = 0
[pid  4996] gettid()                    = 4996
[pid  4996] set_tid_address(0x7bfd424d60) = 4996
[pid  4996] futex(0xa8099640, FUTEX_WAIT_BITSET_PRIVATE, 16386, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
[pid  4993] <... write resumed> )       = 53
[pid  4993] futex(0xa8099640, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  4996] <... futex resumed> )       = 0
[pid  4993] write(1, "syscall pre syscall number:  98 "..., 56 <unfinished ...>
[pid  4996] futex(0xa8099640, FUTEX_WAIT_BITSET_PRIVATE, 16386, NULL, FUTEX_BITSET_MATCH_ANYsyscall pre syscall number:  98 thread_data: 0x31a5000 
 <unfinished ...>
[pid  4993] <... write resumed> )       = 56
[pid  4993] futex(0xa8099640, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  4996] <... futex resumed> )       = 0
[pid  4993] futex(0x7bfd424dd8, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  4993] futex(0xa8099640, FUTEX_WAIT_BITSET_PRIVATE, 16386, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
[pid  4996] <... write resumed> )       = 57
[pid  4996] futex(0xa8099640, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  4996] futex(0x7bfd424dd8, FUTEX_WAIT_BITSET_PRIVATE, 2, NULL, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Try again)
[pid  4993] <... futex resumed> )       = -1 EAGAIN (Try again)
[pid  4993] futex(0xa8099640, FUTEX_WAIT_BITSET_PRIVATE, 16386, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
[pid  4996] futex(0xa8099640, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  4993] <... futex resumed> )       = 0
[pid  4996] <... futex resumed> )       = 1
[pid  4996] mmap(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7c00dc4000
[pid  4996] futex(0xa8099640, FUTEX_WAIT_BITSET_PRIVATE, 16386, NULL, FUTEX_BITSET_MATCH_ANYsyscall pre syscall number:  98 thread_data: 0x31a5000 
 <unfinished ...>
[pid  4993] <... write resumed> )       = 56
[pid  4993] futex(0xa8099640, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  4996] <... futex resumed> )       = 0
[pid  4993] futex(0x7bfff7cd60, FUTEX_WAIT, 4995, NULL <unfinished ...>
[pid  4996] futex(0xa8099640, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  4996] mprotect(0x7c00dc4000, 4096, PROT_NONE) = 0
[pid  4996] sigaltstack({ss_sp=0x7c00dc5000, ss_flags=0, ss_size=32768}, NULL) = 0
[pid  4996] prctl(PR_SET_VMA, PR_SET_VMA_ANON_NAME, 0x7c00dc5000, 32768, "thread signal stack") = 0
[pid  4996] mmap(NULL, 16777216, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfee84000
[pid  4996] mprotect(0x7bff8bc000, 8192, PROT_READ|PROT_WRITE) = 0
[pid  4996] sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}, NULL) = 0
[pid  4996] munmap(0x7c00dc4000, 36864) = 0
[pid  4996] rt_sigprocmask(SIG_BLOCK, ~[RT_1 RT_2 RT_3 RT_4 RT_5], [RTMIN], 8) = 0
[pid  4996] munmap(0x7bfee84000, 16777216) = 0
[pid  4996] write(1, "Exit*** thread exit, thread_data"..., 44Exit*** thread exit, thread_data 0xfba58000
) = 44
[pid  4996] munmap(0x7bfaa58000, 16777216) = 0
[pid  4996] munmap(0x7bfa8d1000, 1601536) = 0
[pid  4996] munmap(0x7bfba58000, 26034176) = 0
[pid  4996] sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}, NULL) = 0
[pid  4996] munmap(0x7c00ded000, 20480) = 0
[pid  4996] set_tid_address(0)          = 4996
[pid  4996] rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2 RT_3], ~[KILL STOP RT_1 RT_2 RT_3 RT_4 RT_5], 8) = 0
[pid  4996] munmap(0x7c00df2000, 20480) = 0
[pid  4996] munmap(0x7c00df7000, 28672) = 0
[pid  4996] exit(0)                     = ?
[pid  4996] +++ exited with 0 +++
`

from the log, i found that when thr tid 4995 exit, the thread 4993 give a syscall 
`[pid  4993] futex(0x7bfff7cd60, FUTEX_WAIT, 4995, NULL <unfinished ...>`
and it's the last record of pid 4993, so i guess the tid 4993 isn's noticed when 4995 exiting, the 4993 pending all the time.

the same application compiled runing in arm-linux is well with no error, `dbm mt`, the syscall strace is like this.
`
[pid 24801] futex(0xffff963312c0, FUTEX_WAIT, 24803, NULL <unfinished ...>
[pid 24803] write(1, "syscall pre syscall number: 233 "..., 57syscall pre syscall number: 233 thread_data: 0x9425d000
) = 57
[pid 24803] madvise(0xffff95b31000, 8253440, MADV_DONTNEED) = 0
[pid 24803] write(1, "syscall pre syscall number:  93 "..., 57syscall pre syscall number:  93 thread_data: 0x9425d000
) = 57
[pid 24803] write(1, "Exit*** thread exit\n", 20Exit*** thread exit
) = 20
[pid 24803] munmap(0xffff928b5000, 16777216) = 0
[pid 24803] munmap(0xffff940d6000, 1601536) = 0
[pid 24803] munmap(0xffff9425d000, 26034176) = 0
[pid 24803] exit(0)                     = ?
`
sorry that the binary file can't be uploaded, but you can compile the .c file, it;s the same.
i have no idea how to debug next, it's good on arm-linux, but the error above on android.
Thanks a lot.

**Comment by whcjb** [comment]
it is the same error when run `dbm geekbench_aarch64`, the strace is the same that the main thread wait for the first child thread to exit which has already exited.
the test is on android.

**Comment by whcjb** [comment]
i tested that the dbm runs well when comment the `tmp1 = pthread_join(thread1,&retival);`
---------------------------------

clone(child_stack=0x785a5ef4e0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x785a5ef500, tls=0x785a5ef588, child_tidptr=0x785a5ef500) = 13822
sched_getscheduler(0)                   = 0 (SCHED_OTHER)
futex(0x785a5ef570, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7855c2add8, FUTEX_WAKE_PRIVATE, 1) = 0
mprotect(0x785e815000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x785e815000, 4096, PROT_READsleep..........................................................
) = 0
mprotect(0x785e815000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x785e815000, 4096, PROT_READ) = 0
munmap(0x785e815000, 4096)              = 0
write(2, "We're done; exiting with status:"..., 35We're done; exiting with status: 0
) = 35
mprotect(0x785e947000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x785e947000, 4096, PROT_READ) = 0
munmap(0x785e947000, 4096)              = 0
exit_group(0)                           = ?
+++ exited with 0 +++
---------------------------------------------------------
so the error come from the futex(wait), or the inconnection between the futex(wake) and futex(wait).
please help.

**Comment by amimo** [comment]
@whcjb @lgeek I have the same issue. After some investigation,  I think the problem may be at [this line](https://github.com/beehive-lab/mambo/blob/05bef40b353e4baece0d80e73ffe63aa6ebfe9d9/syscalls.c#L112), we can't join a thread if it is not attachable?

**Comment by lgeek** [comment]
Thanks both of you. @amimo that makes sense, but nevertheless I can't reproduce the behavior described here on GNU/Linux. I suspect it's a difference in Android's pthreads implementation compared to glibc, I'll take a closer look.

**Comment by lgeek** [comment]
Since MAMBO is linked statically, it will be using the standard library of the system it's compiled on, not of the host machine. This [zip archive](https://github.com/beehive-lab/mambo/files/3837100/mambo.zip) contains the master head I've built on an Arch Linux ARM system. This executable is running the example provided by @whcjb (also compiled on Arch and linked statically) correctly on an Android device.

It would be useful to know if this MAMBO binary can run @whcjb's example compiled with the Android toolchain without hanging.

**Comment by amimo** [comment]
> It would be useful to know if this MAMBO binary can run @whcjb's example compiled with the Android toolchain without hanging.

This MAMBO built can exit normally running @whcjb's example compiled with the Android toolchain.

**Comment by IgWod** [comment]
Since it's an old issue and I have no way of testing it at the moment, I'm going to close it in the effort to clean up the repo. If anyone still requires this fix, please re-open the issue and I can look into it.
