### ISSUE TITLE
vcvtp instruction not handled

### ISSUE THREAD

**Issue by amimo** [beehive-lab/mambo#41]
MAMBO failed to translate this instruction I encountered in Android 9's dynamic linker.

disassembly   : vcvtp.u32.f32   s0, s0
t32 encoding : 0x40,0x0a,0xbe,0xfe

**Comment by IgWod** [comment]
Since it's an old issue and I have no way of testing it at the moment, I'm going to close it in the effort to clean up the repo. If anyone still requires this fix, please re-open the issue and I can look into it.
