### ISSUE TITLE
Unknown A64 instruction: 82

### ISSUE THREAD

**Issue by agusnt** [beehive-lab/mambo#48]
Hello.
I am trying to use Mambo in an AARCH64 processor (Kupeng 920) with CentOS 8 and Kernel X. After compiling the plugins/cachesim (with the makefile, I remove the static flag), I execute the application and get the following error:

`Unknown A64 instruction: 82 at 0xffff8e8048cc (the address change between executions)`

This error happens after a minor CentOS update (kernel version and some libraries). Do you have any idea of how to solve it?

Thank you

More information:

- Processor: Kupeng 920 (TaiShan v110)
- ISA: ARMv8.2-A
- O.S.: CentOS 8.4
- Kernel: kernel-4.18.0-305
- Exec parameters: ./dbm /usr/bin/ls

**Comment by GuillermoCallaghan** [comment]
Hi Agustín,
The reason for the error is (probably) that MAMBO found an `Armv8.1 `or `Armv8.2 `instruction, and MAMBO right now has support for `Arm8.0`, however as a temporary workaround @lgeek made [this patch](https://github.com/beehive-lab/mambo/commit/abf537c8e65b4f2858c75fa1d6c995c7a942a52e). The patch changes the error to a warning so it can be used. Can you try using the latest commit and let us now if the error became a warning and you can use MAMBO?

The warning message looks like this:
```
MAMBO: Unknown A64 instruction: 82 (0xb8a03020) at 0x7f9396c800
Copying it unmodified, but future problems are possible
Report crashes at https://github.com/beehive-lab/mambo
```

Thanks

**Comment by agusnt** [comment]
Hi Guillermo
It works!.

Thank you for the patch and the explanation.
