### ISSUE TITLE
Need help executing 32bit arm binaries on aarch64

### ISSUE THREAD

**Issue by theofficialgman** [beehive-lab/mambo#55]
according to this statement from the abstract of your paper it should be possible to achieve in this software: 

> We present MAMBO-X64, a dynamic binary translator for Linux which executes 32-bit ARM binaries using only the AArch64 instruction set.

My question is, what needs to be done in order to execute an armhf binary on an aarch64 only system using mambo? I can compile mamo on my aarch64 system but attempting to run an armhf binary with `./dbm path_to_binary` just results in `Error reading the ELF executable header: invalid binary class`

for reference this is the elf header of the binary I am trying to execute: `ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV)`

**Comment by GuillermoCallaghan** [comment]
Hi @theofficialgman,
MAMBO is a dynamic binary modification/instrumentation tool, and cannot execute a binary that is compiled to different ISA.
MAMBO-X64 is not MAMBO, you can find information about MAMBO-X64 here [amanieusystems](https://www.amanieusystems.com/technology).

**Comment by theofficialgman** [comment]
ah thanks you for that. I wasn't aware that tango had acquired mambo-x64 and that it is not open source software

**Comment by serentaa** [comment]
> Hi @theofficialgman, MAMBO is a dynamic binary modification/instrumentation tool, and cannot execute a binary that is compiled to different ISA. MAMBO-X64 is not MAMBO, you can find information about MAMBO-X64 here [amanieusystems](https://www.amanieusystems.com/technology).

If commercial use is required, what is the charging standard? Where can I get it?
