### ISSUE TITLE
Handling "uncond_reg_arm" in traces

### ISSUE THREAD

**Issue by alirazeen** [beehive-lab/mambo#6]
I have encountered the case where the trace scanner prints the message `Unknown exit branch type` for the branch type `uncond_reg_arm`. Do I only have to add it to the if and switch statement in `create_trace`? Is it as simple as commit https://github.com/beehive-lab/mambo/commit/236010f7df9ac3620377822417a8ca6cb6b37d56 or would I have to take into account something else?

Thank you for all the help, by the way!

**Comment by lgeek** [comment]
Could you please confirm whether the full message was "Unknown exit branch type in trace head: X"?

If it was, then `uncond_reg_arm` needs to be added both to the if on line 90 and to the switch starting on line 142 (https://github.com/beehive-lab/mambo/blob/236010f7df9ac3620377822417a8ca6cb6b37d56/traces.c#L142) - not the one on line 194 like in the other commit.

**Comment by alirazeen** [comment]
Yep, that was the message, and I did place `uncond_reg_arm` in the right places. Things proceeded to work after that.
